name: my-profile-deployment

on: push

jobs:

  deploy:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Set up application dependencies
        run: pip install -r requirements.txt
        
      - name: Install AWS CDK
        run: npm install -g aws-cdk

      - name: Application bootstrap
        run:  cdk bootstrap

      - name: Deploy
        run:  cdk deploy --require-approval never